PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT ?atoma ?atomb ?atomc
WHERE {
        ?classlhs   owl:unionOf                             ?conja
                 ;  rdf:type                                owl:Class
                 ;  rdfs:subClassOf                         ?classrhs
                 .
        ?conja      rdf:first                               ?atoma
                 ;  rdf:rest/rdf:first                      ?atomb
                    # Ensure this is a binary intersectionOf
                 ;  rdf:rest/rdf:rest                       rdf:nil
                 .
        ?atoma     rdf:type                                 owl:Class 
                 .
        ?atomb     rdf:type                                 owl:Class 
                 .
        ?classrhs   owl:complementOf                        ?atomc
                 ;  rdf:type                                owl:Class
                 .
        ?atomc     rdf:type                                 owl:Class 
                 .
        # Ensure each atom is atomic
        FILTER NOT EXISTS{?atoma owl:unionOf        ?ox }
        FILTER NOT EXISTS{?atoma owl:intersectionOf ?oy } 
        FILTER NOT EXISTS{?atoma owl:complementOf   ?oz } 
        FILTER NOT EXISTS{?atomb owl:unionOf        ?o1 } 
        FILTER NOT EXISTS{?atomb owl:intersectionOf ?o2 } 
        FILTER NOT EXISTS{?atomb owl:complementOf   ?o3 } 
        FILTER NOT EXISTS{?atomc owl:unionOf        ?o4 } 
        FILTER NOT EXISTS{?atomc owl:intersectionOf ?o5 } 
        FILTER NOT EXISTS{?atomc owl:complementOf   ?o6 } 
       } 
GROUP BY ?atoma ?atomb ?atomc ?atomd