PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT ?atoma ?atomb ?atomc
WHERE {
        ?classlhs   owl:unionOf                             ?conja
                 ;  rdf:type                                owl:Class
                 ;  $(TERM)                         ?classrhs
                 .
        ?conja      rdf:first                               ?atoma
                 ;  rdf:rest/rdf:first                      ?atomb
                    # Ensure this is a binary intersectionOf
                 ;  rdf:rest/rdf:rest                       rdf:nil
                 .
        ?atoma     rdf:type                                 owl:Class 
                 .
        ?atomb     rdf:type                                 owl:Class 
                 .
        ?classrhs   owl:someValuesFrom                      ?atomc
                 .
        ?atomc     rdf:type                                 owl:Class 
                 .
       }
GROUP BY ?atoma ?atomb ?atomc