PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT ?subject ?object 
WHERE { ?x       rdfs:subClassOf/owl:someValuesFrom ?object ; 
                 owl:complementOf                   ?subject .
        ?subject rdf:type                           owl:Class . 
        ?object  rdf:type                           owl:Class . 
        FILTER NOT EXISTS{?subject owl:unionOf        ?o1 } 
        FILTER NOT EXISTS{?subject owl:intersectionOf ?o2 } 
        FILTER NOT EXISTS{?subject owl:complementOf   ?o3 } 
        FILTER NOT EXISTS{?object  owl:unionOf        ?o4 } 
        FILTER NOT EXISTS{?object  owl:intersectionOf ?o5 } 
        FILTER NOT EXISTS{?object  owl:complementOf   ?o6 } 
       } 
GROUP BY ?subject ?object 