PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT ?atoma ?atomb
WHERE { ?lhs     $(TERM)                          ?object
                 ; owl:complementOf                       ?atoma
                 .
        ?atoma      rdf:type                              owl:Class
                 .
        # FIXME: would like to write ?object owl:unionOf/owl:Class/rdf:first ?atomb here, but it doesn't work.
        ?object     owl:complementOf                      ?atomb
                 ;  rdf:type                              owl:Class 
                 .
        ?atomb     rdf:type                               owl:Class 
                 .
       } 
GROUP BY ?atoma ?atomb